---
abstract: 'Object interface to Phanfare library'
author:
  - 'Soren Dossing, C<< <netcom at sauber.net> >>'
  - 'Soren Dossing <netcom@sauber.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Pod::Coverage::Moose: 0
  Test::More: 0
  Test::Pod::Coverage: 0
  YAML::Syck: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Phanfare-Class
no_index:
  directory:
    - inc
    - t
requires:
  Cache::Memory: 0
  Date::Parse: 0
  MooseX::Method::Signatures: 0
  WWW::Phanfare::API: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
